name: 'Install Provisioning Profile'
description: 'Install provisioning profiles and uninstall them at the end of the workflow GitHub Action'
inputs:
  base64:
    description: 'Baes64 encoded data in provisioning profile'
    required: false
    default: ''
  path:
    description: 'Provisioning profile path'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
branding:
  icon: "upload-cloud"
  color: "orange"
